repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-added-large-files
  - id: debug-statements
  - id: end-of-file-fixer
- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.730
  hooks:
  - id: mypy
  - id: mypy
    name: mypy, for Py2
    args: ["-2"]
